version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: innovatech_db
    restart: always
    environment:
      MYSQL_DATABASE: innovatech_ops
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_secret
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bd/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./bd/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - innovatech_net

  backend:
    build: ./backend
    container_name: innovatech_backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=innovatech_ops
      - DB_USER=app_user
      - DB_PASSWORD=app_secret
      - CORS_ORIGIN=http://localhost
    depends_on:
      - db
    networks:
      - innovatech_net

  frontend:
    build: ./frontend
    container_name: innovatech_frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://<IP_PUBLICA_EC2>:3001
    networks:
      - innovatech_net

networks:
  innovatech_net:
    driver: bridge

volumes:
  mysql_data: